# Markdown linting rules for Tech Notes Hub
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for details

# Default state for all rules
default: true

# MD001 header-increment - Headers should increment by one level at a time
MD001: true

# MD003 header-style - Header style
MD003:
  style: "atx"  # Use # style headers

# MD004 ul-style - Unordered list style
MD004:
  style: "consistent"

# MD007 ul-indent - Unordered list indentation
MD007:
  indent: 2  # Use 2 spaces for indentation

# MD009 no-trailing-spaces - No trailing spaces
MD009: true

# MD010 no-hard-tabs - No hard tabs
MD010: true

# MD012 no-multiple-blanks - Multiple consecutive blank lines
MD012:
  maximum: 1  # Allow at most 1 blank line

# MD013 line-length - Line length
MD013:
  line_length: 120  # Allow longer lines for code blocks
  code_blocks: false
  tables: false

# MD022 blanks-around-headers - Headers should be surrounded by blank lines
MD022: true

# MD024 no-duplicate-header - Multiple headers with the same content
MD024:
  siblings_only: true  # Allow same title in different nesting

# MD025 single-title/single-h1 - Only one top-level header
MD025: true

# MD026 no-trailing-punctuation - No trailing punctuation in header
MD026:
  punctuation: ".,;:!。，；：！"

# MD029 ol-prefix - Ordered list item prefix
MD029:
  style: "one_or_ordered"  # Use 1. or ordered numbers

# MD031 blanks-around-fences - Fenced code blocks should be surrounded by blank lines
MD031: true

# MD032 blanks-around-lists - Lists should be surrounded by blank lines
MD032: true

# MD033 no-inline-html - No inline HTML
MD033:
  allowed_elements: ["br", "img", "a", "details", "summary"]

# MD034 no-bare-urls - No bare URLs
MD034: true

# MD036 no-emphasis-as-header - No emphasis as header
MD036: true

# MD037 no-space-in-emphasis - No spaces inside emphasis markers
MD037: true

# MD038 no-space-in-code - No spaces inside code span markers
MD038: true

# MD040 fenced-code-language - Fenced code blocks should have a language specified
MD040: true

# MD041 first-line-heading - First line should be a top-level header
MD041: true

# MD046 code-block-style - Code block style
MD046:
  style: "fenced"  # Use ```code``` style
